import { useEffect, useMemo } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Logo } from '../../components/Logo';
import { Overview } from './sections/Overview';
import { Simulator } from './sections/Simulator';
import { Trial } from './sections/Trial';
import { Evidence } from './sections/Evidence';
import { Methods } from './sections/Methods';
import './rlfda.css';

const BASE = '/RL-FDA-Approval';

const SECTIONS = [
  { slug: '', label: 'Overview', title: 'Reinforcement learning for cardiac device submissions' },
  { slug: 'simulator', label: 'Simulator', title: 'Live simulator' },
  { slug: 'trial', label: 'In-silico trial', title: 'In-silico trial' },
  { slug: 'evidence', label: 'Evidence', title: 'Credibility and evidence' },
  { slug: 'methods', label: 'Methods', title: 'Model and methods' },
] as const;

export function RlFdaPage() {
  const location = useLocation();
  const slug = useMemo(() => {
    const rest = location.pathname.slice(BASE.length).replace(/^\/+|\/+$/g, '');
    return SECTIONS.some((s) => s.slug === rest) ? rest : '';
  }, [location.pathname]);

  const active = SECTIONS.find((s) => s.slug === slug) ?? SECTIONS[0];

  useEffect(() => {
    document.title = `${active.title} — BUMP`;
    window.scrollTo(0, 0);
    return () => {
      document.title = 'BUMP — Emergency Cardiac Response';
    };
  }, [active]);

  return (
    <div className="rl">
      <header className="rl-head">
        <div className="rl-head__bar">
          <Link to="/" className="rl-head__brand" aria-label="BUMP home">
            <Logo height={30} showText={false} />
            <span className="rl-head__brand-text">Regulatory Simulation</span>
          </Link>
          <nav className="rl-nav" aria-label="Programme sections">
            {SECTIONS.map((s) => (
              <Link
                key={s.slug}
                to={s.slug ? `${BASE}/${s.slug}` : BASE}
                className={`rl-nav__link ${s.slug === slug ? 'rl-nav__link--active' : ''}`}
              >
                {s.label}
              </Link>
            ))}
          </nav>
        </div>
      </header>

      <main>
        {slug === '' && <Overview />}
        {slug === 'simulator' && <Simulator />}
        {slug === 'trial' && <Trial />}
        {slug === 'evidence' && <Evidence />}
        {slug === 'methods' && <Methods />}
      </main>

      <footer className="rl-foot">
        <div className="rl__inner">
          <div className="rl-foot__links">
            <Link to="/">BUMP home</Link>
            <Link to="/demo">Detection demo</Link>
            <a
              href="https://github.com/aarushkandukoori/bump-detection"
              target="_blank"
              rel="noopener noreferrer"
            >
              Detection pipeline on GitHub
            </a>
          </div>
          <p>
            Engineering research prototype. The simulator, the controllers and the trial results on
            these pages are computational work, not clinical evidence. Nothing here is a medical
            device, has been reviewed by any regulator, or should be used to guide the care of any
            patient. Every figure is generated by the code described in the methods section and is
            reproducible from the seeds recorded alongside it.
          </p>
          <p style={{ marginTop: 10 }}>
            &copy; {new Date().getFullYear()} BUMP Medical, Inc.
          </p>
        </div>
      </footer>
    </div>
  );
}
