/**
 * Shared environment scaffolding.
 *
 * Every program in the platform presents the same interface to the learning
 * code: a fixed-length real observation vector, a discrete action index, a
 * scalar reward, and a termination flag. Keeping that interface identical
 * across programs is what lets one trainer, one off-policy evaluator and one
 * trial engine serve all three, and it is also what makes the credibility
 * argument transferable: the evidence generated for one program's controller
 * is generated by the same machinery as for the others.
 */

import type { Observation } from '../engine/sensors.ts';

export interface StepResult {
  /** Encoded feature vector for the policy. */
  obs: Float64Array;
  /** The full observation, for display and for the guideline comparator. */
  observation: Observation;
  reward: number;
  done: boolean;
  /** Whether the safety shield modified the proposed action. */
  shieldIntervened: boolean;
  /** The rule that fired, if any. */
  shieldRule: string | null;
  /** The action actually executed after shielding. */
  executedAction: number;
}

export interface Environment {
  readonly nActions: number;
  readonly nObs: number;
  readonly actionLabels: readonly string[];
  reset(): Float64Array;
  step(action: number): StepResult;
}

/** Squashing that keeps features in a comparable range without clipping. */
export function scale(x: number, centre: number, spread: number): number {
  return Math.tanh((x - centre) / spread);
}

/** Linear normalisation to roughly [0, 1], clamped. */
export function unit(x: number, lo: number, hi: number): number {
  return Math.min(1, Math.max(0, (x - lo) / (hi - lo)));
}

/**
 * Encode an observation as the feature vector the policy consumes.
 *
 * Feature choice is a regulatory artefact, not an implementation detail: the
 * marketing submission has to state what the model's inputs are, and a
 * feature the device cannot actually measure is a feature that invalidates
 * the submission. Every element below corresponds to something the sensing
 * layer produces or something the device itself administered and can
 * therefore account for exactly.
 */
export const FEATURE_NAMES = [
  'heart rate',
  'heart rate trend',
  'RR variability',
  'mean arterial pressure',
  'pressure reading age',
  'pressure trend',
  'perfusion index',
  'QRS duration',
  'AV conduction ratio',
  'atrial rate',
  'pacing active',
  'pacing output',
  'pacing rate',
  'apparent capture',
  'cumulative atropine',
  'time since last atropine',
  'atropine effect realised',
  'dopamine rate',
  'epinephrine rate',
  'isoproterenol rate',
  'elapsed time',
  'charted denervation',
  'charted infranodal disease',
  'age',
] as const;

export const N_FEATURES = FEATURE_NAMES.length;

export function encode(o: Observation, out?: Float64Array): Float64Array {
  const v = out ?? new Float64Array(N_FEATURES);
  v[0] = scale(o.heartRate, 60, 25);
  v[1] = scale(o.heartRateTrend, 0, 15);
  v[2] = scale(o.rrVariability, 40, 60);
  v[3] = scale(o.map, 70, 22);
  v[4] = unit(o.mapAgeSeconds, 0, 120);
  v[5] = scale(o.mapTrend, 0, 12);
  v[6] = scale(o.perfusionIndex, 1, 0.6);
  v[7] = scale(o.qrsWidth, 0.11, 0.05);
  v[8] = o.conductionRatio;
  v[9] = scale(o.atrialRate, 75, 30);
  v[10] = o.pacingOn ? 1 : 0;
  v[11] = unit(o.pacingOutputMa, 0, 140);
  v[12] = unit(o.pacingRate, 40, 110);
  v[13] = o.apparentCapture ? 1 : 0;
  v[14] = unit(o.atropineTotalMg, 0, 3);
  v[15] = unit(o.secondsSinceAtropine, 0, 900);
  v[16] = o.atropineEffectRealised;
  v[17] = unit(o.dopamineRate, 0, 20);
  v[18] = unit(o.epinephrineRate, 0, 10);
  v[19] = unit(o.isoproterenolRate, 0, 10);
  v[20] = unit(o.elapsedSeconds, 0, 2700);
  v[21] = o.knownDenervated ? 1 : 0;
  v[22] = o.knownInfranodal ? 1 : 0;
  v[23] = scale(o.ageYears, 70, 20);
  return v;
}
