/**
 * The integrated cardiac model.
 *
 * Couples the four sub-models into a single hybrid system:
 *
 *   conduction (discrete events)  ->  chamber activation
 *   activation + autonomic + drug ->  circulation (continuous ODE)
 *   circulation                   ->  arterial pressure
 *   arterial pressure             ->  baroreflex  ->  autonomic state
 *   dosing commands               ->  pharmacokinetics -> drug effect
 *
 * Integration scheme
 * ------------------
 * The eight circulation volumes are advanced with classical fixed-step
 * fourth-order Runge-Kutta. The activation functions are evaluated at each
 * Runge-Kutta stage time rather than being frozen across the step, because
 * chamber elastance is the fastest-varying quantity in the system and
 * freezing it would dominate the truncation error.
 *
 * The autonomic effector states and every pharmacokinetic compartment are
 * linear first-order systems and are advanced separately: the drug
 * compartments with their exact exponential solution, the reflex effectors
 * with a matched first-order update. Splitting the stiff-but-linear slow
 * states out of the Runge-Kutta loop is both faster and more accurate than
 * folding them in.
 *
 * The default step of 1 ms is more than an order of magnitude below the
 * fastest time constant in the system (roughly 7 ms for left ventricular
 * ejection through the aortic valve at peak elastance). The solution
 * verification study in the credibility record demonstrates convergence.
 */

import {
  BASELINE_CIRCULATION,
  circulationDerivatives,
  cloneCirculation,
  evaluateCirculation,
  N_CIRC,
  V_AO,
  V_LA,
  V_LV,
  V_PA,
  V_PU,
  V_RA,
  V_RV,
  V_VC,
  type CirculationDrive,
  type CirculationOutputs,
  type CirculationParams,
} from './circulation.ts';
import {
  atrialSystoleDuration,
  doubleHillDriver,
  systoleDuration,
} from './activation.ts';
import {
  BASELINE_CONDUCTION,
  ConductionSystem,
  PACING_OFF,
  type ActivationEvent,
  type ConductionDrive,
  type ConductionParams,
  type PacingConfig,
} from './conduction.ts';
import {
  Baroreflex,
  BASELINE_BAROREFLEX,
  newAutonomicOutput,
  type AutonomicOutput,
  type BaroreflexParams,
} from './autonomic.ts';
import {
  adrenergicEffect,
  DRUGS,
  giveAtropine,
  muscarinicBlockade,
  newDrugState,
  paradoxicalVagalGain,
  stepDrug,
  type DrugId,
  type DrugState,
} from './pharmacology.ts';
import { Rng } from './rng.ts';
import { CALIBRATED } from './calibrated.ts';
import { flowToCardiacOutput } from './units.ts';

export interface RespirationParams {
  /** Breaths per minute. */
  rate: number;
  /** End-expiratory intrathoracic pressure, mmHg. */
  pEndExpiratory: number;
  /** Inspiratory swing, mmHg (positive number, subtracted at inspiration). */
  swing: number;
}

export const BASELINE_RESPIRATION: RespirationParams = {
  rate: 14,
  pEndExpiratory: -4,
  swing: 3,
};

export interface ModelConfig {
  circulation: CirculationParams;
  conduction: ConductionParams;
  baroreflex: BaroreflexParams;
  respiration: RespirationParams;
  /** Total stressed blood volume, mL. */
  stressedVolume: number;
  /** Body weight, kg (drug dosing and cardiac index). */
  weightKg: number;
  /** Height, cm. */
  heightCm: number;
  /** Integration step, s. */
  dt: number;
  seed: number;
}

/**
 * The reference healthy adult: 78 kg, 172 cm, with the calibrated parameter
 * set applied. Every virtual subject is generated by perturbing this config.
 */
export function defaultModelConfig(seed = 1): ModelConfig {
  const circulation = cloneCirculation(BASELINE_CIRCULATION);
  circulation.ao.e = CALIBRATED.aoElastance;
  circulation.vc.e = CALIBRATED.vcElastance;
  circulation.pa.e = CALIBRATED.paElastance;
  circulation.pu.e = CALIBRATED.puElastance;
  circulation.rSys = CALIBRATED.rSys;
  circulation.rPul = CALIBRATED.rPul;
  circulation.lv.eEs = CALIBRATED.lvEes;
  circulation.lv.p0 = CALIBRATED.lvP0;
  circulation.lv.lambda = CALIBRATED.lvLambda;
  circulation.rv.eEs = CALIBRATED.rvEes;
  circulation.la.p0 = CALIBRATED.laP0;
  circulation.ra.p0 = CALIBRATED.raP0;
  circulation.pericardium.p0 = CALIBRATED.pericardiumP0;
  const conduction = { ...BASELINE_CONDUCTION };
  conduction.intrinsicSinusRate = CALIBRATED.intrinsicSinusRate;
  return {
    circulation,
    conduction,
    baroreflex: { ...BASELINE_BAROREFLEX },
    respiration: { ...BASELINE_RESPIRATION },
    stressedVolume: CALIBRATED.stressedVolume,
    weightKg: 78,
    heightCm: 172,
    dt: 0.001,
    seed,
  };
}

/**
 * Steady-state fraction of the stressed blood volume held by each compartment,
 * in state-vector order (LV, AO, VC, RA, RV, PA, PU, LA). Measured from the
 * converged calibrated reference subject.
 */
export const INITIAL_VOLUME_FRACTION = [
  0.04048, 0.07644, 0.20902, 0.02398, 0.02226, 0.02414, 0.57245, 0.03123,
] as const;

/**
 * Rate-dependent contractility: the force-frequency (Bowditch) relation.
 *
 * Myocardial force development depends on stimulation rate through
 * frequency-dependent calcium loading. In human myocardium the relation rises
 * to a peak somewhere around 150-170 min^-1; at a normal resting rate the
 * muscle is developing only about 57 per cent of that peak, and at profoundly
 * slow rates around 15 min^-1 only about 47 per cent.
 *
 * This matters here more than it would in most models. A model that holds
 * end-systolic elastance fixed while the rate falls lets the Frank-Starling
 * mechanism compensate without limit, and therefore over-predicts stroke
 * volume at exactly the rates this platform exists to reason about. Including
 * the relation is the difference between a bradycardia that looks survivable
 * and one that behaves the way the clinical literature describes.
 *
 * The form is a two-slope logarithmic fit through the published anchors,
 * normalised to unity at 72 min^-1. It is phenomenological, and is recorded
 * as such in the model credibility record.
 */
export function forceFrequencyFactor(rateBpm: number): number {
  const hr = Math.min(Math.max(rateBpm, 12), 200);
  const slopeLow = 0.133;
  const slopeHigh = 0.7;
  // Smooth blend of the two slopes about the reference rate.
  const w = 1 / (1 + Math.exp(-(hr - 72) / 18));
  const slope = slopeLow + (slopeHigh - slopeLow) * w;
  return Math.min(1.65, Math.max(0.72, 1 + slope * Math.log(hr / 72)));
}

/** Instantaneous, fully observable model state. Ground truth, not sensed. */
export interface Snapshot {
  t: number;
  pAo: number;
  pLv: number;
  pLa: number;
  pRa: number;
  pPa: number;
  pPu: number;
  vLv: number;
  vLa: number;
  vRv: number;
  activationLv: number;
  /** Beat-resolved values, updated once per ventricular contraction. */
  heartRate: number;
  strokeVolume: number;
  cardiacOutput: number;
  ejectionFraction: number;
  edv: number;
  esv: number;
  map: number;
  systolic: number;
  diastolic: number;
  /** Estimated central venous pressure, mmHg (mean right atrial pressure). */
  cvp: number;
  /** Mean pulmonary capillary wedge, approximated by mean LA pressure. */
  pcwp: number;
  /** Systemic vascular resistance actually in force, mmHg*s/mL. */
  svr: number;
  /** Autonomic and drug state. */
  sympatheticTone: number;
  vagalTone: number;
  muscarinicBlockade: number;
  inotropy: number;
  /** Rate-dependent contractility factor currently in force. */
  forceFrequency: number;
  /** Cumulative atropine, mg. */
  atropineTotal: number;
  /** Rhythm description. */
  rhythmSource: string;
  qrsWidth: number;
  avConductionRatio: number;
  /** Oxygen delivery index proxy: cardiac index x arterial content, L/min/m2. */
  cardiacIndex: number;
}

/** Rolling window mean over a fixed number of samples. */
class RollingMean {
  private buf: Float64Array;
  private idx = 0;
  private filled = 0;
  private sum = 0;
  constructor(n: number, initial: number) {
    this.buf = new Float64Array(n);
    this.buf.fill(initial);
    this.sum = initial * n;
    this.filled = n;
  }
  push(v: number): number {
    this.sum -= this.buf[this.idx];
    this.buf[this.idx] = v;
    this.sum += v;
    this.idx = (this.idx + 1) % this.buf.length;
    if (this.filled < this.buf.length) this.filled++;
    return this.sum / this.buf.length;
  }
  get value(): number {
    return this.sum / this.buf.length;
  }
}

export class CardiacModel {
  readonly cfg: ModelConfig;
  readonly y: Float64Array;
  readonly conduction: ConductionSystem;
  readonly baro: Baroreflex;
  readonly drugs: Record<DrugId, DrugState>;
  readonly rng: Rng;
  t = 0;

  private k1: Float64Array;
  private k2: Float64Array;
  private k3: Float64Array;
  private k4: Float64Array;
  private ytmp: Float64Array;
  private drive: CirculationDrive;
  private auto: AutonomicOutput;
  private out: CirculationOutputs;

  /** Activation bookkeeping. */
  private atrialOnset = -10;
  private ventricularOnset = -10;
  private atrialDur = 0.15;
  private ventricularDur = 0.28;

  /** Beat-resolved measurement accumulators. */
  private beatMinV = 1e9;
  private beatMaxV = -1e9;
  private beatMinP = 1e9;
  private beatMaxP = -1e9;
  /** Net volume ejected through the aortic valve during the current beat, mL. */
  private beatEjected = 0;
  /** Net volume crossing the mitral valve during the current beat, mL. */
  private beatFilled = 0;
  private mapMean: RollingMean;
  private cvpMean: RollingMean;
  private pcwpMean: RollingMean;
  private coMean: RollingMean;

  heartRate = 72;
  /**
   * Rate signal driving the force-frequency relation, low-passed because
   * frequency-dependent calcium loading develops over tens of beats rather
   * than instantaneously.
   */
  private ffrRate = 72;
  strokeVolume = 70;
  /** (EDV - ESV); equals strokeVolume only with competent valves. */
  strokeVolumeGeometric = 70;
  mitralInflow = 70;
  cardiacOutput = 5.0;
  edv = 120;
  esv = 50;
  systolic = 120;
  diastolic = 78;
  beatCount = 0;
  /** Set true when the model has entered an unrecoverable state. */
  arrested = false;
  /** Number of times a compartment volume had to be clamped at zero. */
  volumeClampEvents = 0;
  /** Total volume added by clamping, mL. Must be zero in a valid run. */
  volumeClampedMl = 0;

  constructor(cfg: ModelConfig) {
    this.cfg = cfg;
    this.rng = new Rng(cfg.seed);
    this.y = new Float64Array(N_CIRC);
    this.k1 = new Float64Array(N_CIRC);
    this.k2 = new Float64Array(N_CIRC);
    this.k3 = new Float64Array(N_CIRC);
    this.k4 = new Float64Array(N_CIRC);
    this.ytmp = new Float64Array(N_CIRC);
    this.conduction = new ConductionSystem(cfg.conduction, this.rng, 0);
    this.baro = new Baroreflex(cfg.baroreflex, cfg.circulation.lv.eEs);
    this.auto = newAutonomicOutput();
    this.drugs = {
      atropine: newDrugState(),
      epinephrine: newDrugState(),
      dopamine: newDrugState(),
      isoproterenol: newDrugState(),
      norepinephrine: newDrugState(),
      dobutamine: newDrugState(),
    };
    this.out = {
      pLv: 0, pRv: 0, pLa: 0, pRa: 0, pAo: 0, pVc: 0, pPa: 0, pPu: 0,
      pPericardium: 0, qMitral: 0, qAortic: 0, qTricuspid: 0, qPulmonic: 0,
      qSys: 0, qPul: 0, qVc: 0, qPu: 0,
    };
    this.drive = {
      eLv: 0, eRv: 0, eLa: 0, eRa: 0,
      inotropyLv: 1, inotropyRv: 1, svrScale: 1,
      venousUnstressedDelta: 0, pThoracic: cfg.circulation.pThoracic,
    };

    // Initial distribution of the stressed blood volume, taken from the
    // converged steady state of the calibrated reference subject. Starting
    // from the attractor rather than from a guess means no compartment is
    // driven transiently negative on the first steps, which is what makes
    // the volume-conservation guarantee below exact rather than approximate.
    for (let i = 0; i < N_CIRC; i++) this.y[i] = INITIAL_VOLUME_FRACTION[i] * cfg.stressedVolume;

    const w = Math.max(1, Math.round(2.0 / cfg.dt));
    this.mapMean = new RollingMean(w, 92);
    this.cvpMean = new RollingMean(w, 5);
    this.pcwpMean = new RollingMean(w, 9);
    this.coMean = new RollingMean(w, 83);
  }

  /** Intrathoracic pressure at time t, mmHg. */
  private thoracicPressure(t: number): number {
    const r = this.cfg.respiration;
    const phase = ((t * r.rate) / 60) % 1;
    // Smooth inspiratory trough over the first 40% of the cycle.
    const insp = phase < 0.4 ? Math.sin((phase / 0.4) * Math.PI) : 0;
    return r.pEndExpiratory - r.swing * insp;
  }

  /** Evaluate all four chamber activations at absolute time `t`. */
  private activations(t: number, d: CirculationDrive): void {
    const a = doubleHillDriver(t - this.atrialOnset, this.atrialDur);
    const v = doubleHillDriver(t - this.ventricularOnset, this.ventricularDur);
    d.eLa = a;
    d.eRa = a;
    d.eLv = v;
    d.eRv = v;
  }

  /** One fourth-order Runge-Kutta step of the circulation volumes. */
  private rk4(dt: number): void {
    const p = this.cfg.circulation;
    const d = this.drive;
    const t = this.t;

    d.pThoracic = this.thoracicPressure(t);
    this.activations(t, d);
    circulationDerivatives(evaluateCirculation(this.y, 0, p, d, this.out), this.k1, 0);

    const half = dt * 0.5;
    for (let i = 0; i < N_CIRC; i++) this.ytmp[i] = this.y[i] + half * this.k1[i];
    d.pThoracic = this.thoracicPressure(t + half);
    this.activations(t + half, d);
    circulationDerivatives(evaluateCirculation(this.ytmp, 0, p, d, this.out), this.k2, 0);

    for (let i = 0; i < N_CIRC; i++) this.ytmp[i] = this.y[i] + half * this.k2[i];
    circulationDerivatives(evaluateCirculation(this.ytmp, 0, p, d, this.out), this.k3, 0);

    for (let i = 0; i < N_CIRC; i++) this.ytmp[i] = this.y[i] + dt * this.k3[i];
    d.pThoracic = this.thoracicPressure(t + dt);
    this.activations(t + dt, d);
    circulationDerivatives(evaluateCirculation(this.ytmp, 0, p, d, this.out), this.k4, 0);

    const s = dt / 6;
    for (let i = 0; i < N_CIRC; i++) {
      this.y[i] += s * (this.k1[i] + 2 * this.k2[i] + 2 * this.k3[i] + this.k4[i]);
      // Volumes are physically non-negative. This guard is never active in a
      // valid simulation, and every activation is counted rather than being
      // applied silently: a non-zero count invalidates the conservation
      // claim and is reported by the verification suite.
      if (this.y[i] < 0) {
        this.volumeClampEvents++;
        this.volumeClampedMl += -this.y[i];
        this.y[i] = 0;
      }
    }

    // Final evaluation at the accepted state, so the reported pressures and
    // flows are consistent with the state that was actually stored.
    d.pThoracic = this.thoracicPressure(t + dt);
    this.activations(t + dt, d);
    evaluateCirculation(this.y, 0, p, this.drive, this.out);
  }

  /**
   * Advance the whole model by one integration step.
   *
   * `infusions` maps drug ids to their current infusion rate in the drug's
   * clinical dose unit; conversion to mass per second happens here so that
   * weight-based units are handled in exactly one place.
   */
  step(pacing: PacingConfig = PACING_OFF, infusions: Partial<Record<DrugId, number>> = {}): void {
    const dt = this.cfg.dt;

    // 1. Drug state, and the aggregate receptor effects it produces.
    for (const id of Object.keys(DRUGS) as DrugId[]) {
      const m = DRUGS[id];
      const rate = infusions[id] ?? 0;
      let massPerSecond = 0;
      if (rate > 0) {
        massPerSecond = m.doseUnit.includes('/kg/min')
          ? (rate * this.cfg.weightKg) / 60
          : m.doseUnit.includes('/min')
            ? rate / 60
            : 0;
      }
      this.drugs[id].infusion = rate;
      stepDrug(m, this.drugs[id], dt, massPerSecond);
    }
    const adr = adrenergicEffect(this.drugs);
    const block = muscarinicBlockade(this.drugs.atropine.ce);
    const paradox = paradoxicalVagalGain(this.drugs.atropine);

    // 2. Conduction, driven by the autonomic state computed on the previous
    //    step (a one-step lag of 1 ms, far below any physiological latency).
    const cd: ConductionDrive = {
      vagalTone: this.auto.vagalTone + paradox,
      sympatheticTone: this.auto.sympatheticTone,
      betaChronotropy: adr.chronotropy,
      muscarinicBlockade: block,
      respiratoryPhase: ((this.t * this.cfg.respiration.rate) / 60) % 1,
    };
    const events = this.conduction.step(this.t, dt, cd, pacing);
    this.applyEvents(events);

    // 3. Circulation.
    this.ffrRate += ((this.heartRate - this.ffrRate) / 20) * dt;
    const ffr = forceFrequencyFactor(this.ffrRate);
    this.drive.inotropyLv = this.auto.inotropyLv * adr.inotropy * ffr;
    this.drive.inotropyRv = this.auto.inotropyRv * adr.inotropy * ffr;
    this.drive.svrScale = this.auto.svrScale * adr.svrScale;
    this.drive.venousUnstressedDelta = this.auto.venousUnstressedDelta + adr.venousUnstressed;
    this.rk4(dt);

    // 4. Baroreflex, sensing the instantaneous aortic pressure.
    this.baro.step(this.out.pAo, dt, this.auto);

    // 5. Measurement accumulators.
    this.mapMean.push(this.out.pAo);
    this.cvpMean.push(this.out.pRa);
    this.pcwpMean.push(this.out.pLa);
    this.coMean.push(this.out.qAortic);
    this.beatEjected += this.out.qAortic * dt;
    this.beatFilled += this.out.qMitral * dt;
    const v = this.y[V_LV];
    if (v < this.beatMinV) this.beatMinV = v;
    if (v > this.beatMaxV) this.beatMaxV = v;
    if (this.out.pAo < this.beatMinP) this.beatMinP = this.out.pAo;
    if (this.out.pAo > this.beatMaxP) this.beatMaxP = this.out.pAo;

    this.t += dt;

    if (this.mapMean.value < 20 && this.t > 5) this.arrested = true;
  }

  /**
   * Optional sink for depolarisation events, used by the display layer to
   * synthesise a surface electrocardiogram. Null during training, so the
   * training path allocates nothing for a trace nobody looks at.
   */
  onActivation: ((e: ActivationEvent) => void) | null = null;

  /** React to depolarisation events by starting a chamber contraction. */
  private applyEvents(events: ActivationEvent[]): void {
    for (const e of events) {
      this.onActivation?.(e);
      if (e.nonCapture) continue;
      if (e.chamber === 'atrium') {
        this.atrialOnset = e.time;
        this.atrialDur = atrialSystoleDuration(this.conduction.lastAtrialInterval);
      } else {
        // Close out the beat that just ended before starting the next.
        this.closeBeat();
        this.ventricularOnset = e.time;
        this.ventricularDur = systoleDuration(this.conduction.lastVentricularInterval);
      }
    }
  }

  /** Finalise beat-resolved measurements at each ventricular activation. */
  private closeBeat(): void {
    if (this.beatMaxV > this.beatMinV && this.beatCount >= 0) {
      this.edv = this.beatMaxV;
      this.esv = this.beatMinV;
      // Stroke volume is the net forward volume through the aortic valve,
      // which is the quantity that actually perfuses the body. It differs
      // from (EDV - ESV) whenever a valve is incompetent, so both are kept.
      this.strokeVolume = Math.max(0, this.beatEjected);
      this.strokeVolumeGeometric = Math.max(0, this.edv - this.esv);
      this.mitralInflow = this.beatFilled;
      this.heartRate = 60 / Math.min(Math.max(this.conduction.lastVentricularInterval, 0.2), 8);
      this.cardiacOutput = flowToCardiacOutput(this.strokeVolume * (this.heartRate / 60));
      this.systolic = this.beatMaxP;
      this.diastolic = this.beatMinP;
      this.beatCount++;
    }
    this.beatMinV = 1e9;
    this.beatMaxV = -1e9;
    this.beatMinP = 1e9;
    this.beatMaxP = -1e9;
    this.beatEjected = 0;
    this.beatFilled = 0;
  }

  /** True once an atropine-induced conduction collapse has been triggered. */
  atropineCollapse = false;

  /** Deliver an atropine dose. */
  giveAtropine(doseMg: number, route: 'iv' | 'im' = 'iv'): void {
    giveAtropine(this.drugs.atropine, doseMg, route);
    if (this.conduction.notifyAtropine()) this.atropineCollapse = true;
  }

  /** Body surface area, m^2 (Du Bois). */
  get bsa(): number {
    return 0.007184 * Math.pow(this.cfg.heightCm, 0.725) * Math.pow(this.cfg.weightKg, 0.425);
  }

  /** Mean arterial pressure over the trailing measurement window, mmHg. */
  get map(): number {
    return this.mapMean.value;
  }

  /** Flow-weighted cardiac output over the trailing window, L/min. */
  get meanCardiacOutput(): number {
    return flowToCardiacOutput(this.coMean.value);
  }

  snapshot(out?: Snapshot): Snapshot {
    const s: Snapshot = out ?? ({} as Snapshot);
    s.t = this.t;
    s.pAo = this.out.pAo;
    s.pLv = this.out.pLv;
    s.pLa = this.out.pLa;
    s.pRa = this.out.pRa;
    s.pPa = this.out.pPa;
    s.pPu = this.out.pPu;
    s.vLv = this.y[V_LV];
    s.vLa = this.y[V_LA];
    s.vRv = this.y[V_RV];
    s.activationLv = this.drive.eLv;
    s.heartRate = this.heartRate;
    s.strokeVolume = this.strokeVolume;
    s.cardiacOutput = this.cardiacOutput;
    s.edv = this.edv;
    s.esv = this.esv;
    s.ejectionFraction = this.edv > 0 ? this.strokeVolumeGeometric / this.edv : 0;
    s.map = this.mapMean.value;
    s.systolic = this.systolic;
    s.diastolic = this.diastolic;
    s.cvp = this.cvpMean.value;
    s.pcwp = this.pcwpMean.value;
    s.svr = this.cfg.circulation.rSys * this.drive.svrScale;
    s.sympatheticTone = this.auto.sympatheticTone;
    s.vagalTone = this.auto.vagalTone;
    s.muscarinicBlockade = muscarinicBlockade(this.drugs.atropine.ce);
    s.inotropy = this.drive.inotropyLv;
    s.forceFrequency = forceFrequencyFactor(this.ffrRate);
    s.atropineTotal = this.drugs.atropine.cumulative;
    s.rhythmSource = this.conduction.lastSource;
    s.qrsWidth = this.conduction.lastQrsWidth;
    s.avConductionRatio = this.conduction.conductionRatio;
    s.cardiacIndex = s.cardiacOutput / this.bsa;
    return s;
  }

  /**
   * Direct access to the last evaluated pressures and flows.
   *
   * Exposed for verification and measurement code that needs instantaneous
   * quantities rather than the beat-resolved snapshot.
   */
  snapshotRaw(): CirculationOutputs & {
    vLv: number; vLa: number; vRv: number; vAo: number; eLv: number;
  } {
    const o = this.out as CirculationOutputs & {
      vLv: number; vLa: number; vRv: number; vAo: number; eLv: number;
    };
    o.vLv = this.y[V_LV];
    o.vLa = this.y[V_LA];
    o.vRv = this.y[V_RV];
    o.vAo = this.y[V_AO];
    o.eLv = this.drive.eLv;
    return o;
  }

  /** Total stressed volume currently in the circuit, mL (conservation check). */
  get circuitVolume(): number {
    let v = 0;
    for (let i = 0; i < N_CIRC; i++) v += this.y[i];
    return v;
  }

  /** Compartment volumes, for diagnostics. */
  volumes(): Record<string, number> {
    return {
      lv: this.y[V_LV], ao: this.y[V_AO], vc: this.y[V_VC], ra: this.y[V_RA],
      rv: this.y[V_RV], pa: this.y[V_PA], pu: this.y[V_PU], la: this.y[V_LA],
    };
  }

  /** Run for `seconds` with a constant therapy, discarding output. */
  advance(seconds: number, pacing: PacingConfig = PACING_OFF, infusions: Partial<Record<DrugId, number>> = {}): void {
    const n = Math.round(seconds / this.cfg.dt);
    for (let i = 0; i < n; i++) this.step(pacing, infusions);
  }
}
